# Generated by Django 5.2.13 on 2026-04-16 19:26

import api.models
import api.validators
import datetime
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('brief', models.TextField(blank=True, null=True, verbose_name='Brief')),
                ('image', models.ImageField(blank=True, null=True, upload_to='api/organizations/images', validators=[api.validators.validate_file_size], verbose_name='Image')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Identity Card, Proof of Address', max_length=100, verbose_name='Document Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Document Description')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Is Mandatory')),
            ],
            options={
                'verbose_name': 'Required Document',
                'verbose_name_plural': 'Required Documents',
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
            options={
                'verbose_name': 'Work Day/Operating Hour',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude', max_digits=9, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'unique_together': {('address', 'city', 'country'), ('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[api.validators.ExactLengthValidator(14)], verbose_name='National ID')),
                ('birth_date', models.DateField(blank=True, null=True, validators=[api.validators.validate_birth_date], verbose_name='Birth Date')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='api/clients/images', validators=[api.validators.validate_file_size], verbose_name='Client Image')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='Is Authenticated')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address', verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the appointment request.', verbose_name='Date')),
                ('start_time', models.TimeField(help_text='The start time of the appointment request.', verbose_name='Start Time')),
                ('end_time', models.TimeField(help_text='The end time of the appointment request.', verbose_name='End Time')),
                ('reschedule_attempts', models.PositiveIntegerField(default=0, help_text='Number of times this appointment has been rescheduled.', verbose_name='Reschedule Attempts')),
                ('want_reminder', models.BooleanField(default=False, help_text='Indicates whether the client wants a reminder for the appointment.', verbose_name='Want Reminder')),
                ('additional_info', models.TextField(blank=True, help_text='Any additional information the client wants to provide for the appointment.', null=True, verbose_name='Additional Info')),
                ('paid', models.BooleanField(default=False, help_text='Indicates whether the appointment has been paid for.', verbose_name='Paid')),
                ('amount_to_pay', models.DecimalField(blank=True, decimal_places=2, help_text='The amount to be paid for the appointment. If 0, it means the appointment is free or already paid.', max_digits=10, null=True, verbose_name='Amount to Pay')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(help_text='The user who made the appointment request.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.models.get_upload_path, validators=[api.validators.validate_file_size], verbose_name='File')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_documents', to='api.appointment')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.requireddocument')),
            ],
            options={
                'verbose_name': 'Appointment Document',
                'verbose_name_plural': 'Appointment Documents',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('duration', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60))], verbose_name='Duration')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='api/services/images', verbose_name='Service Image')),
                ('currency', models.CharField(default='EGP', max_length=3, validators=[api.validators.ExactLengthValidator(3)], verbose_name='Currency')),
                ('reschedule_limit', models.PositiveIntegerField(default=0, help_text='Maximum number of times an appointment can be rescheduled.', verbose_name='Reschedule limit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.organization', verbose_name='Oraganization')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='api.service', verbose_name='Service'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.address', verbose_name='Address')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.organization', verbose_name='Oraganization')),
                ('services', models.ManyToManyField(blank=True, help_text='Branch offered Services', related_name='branch_services', to='api.service')),
                ('operating_hours', models.ManyToManyField(blank=True, related_name='branches', to='api.workday', verbose_name='Branch Operating Hours')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='ServiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_operational', models.BooleanField(default=True, verbose_name='Is Operational')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_counters', to='api.branch', verbose_name='Branch')),
                ('service', models.ForeignKey(help_text='Service this counter offers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to='api.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Counter',
                'verbose_name_plural': 'Service Counters',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='counter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.servicecounter', verbose_name='Service Counter'),
        ),
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(help_text='Write Feedback to the Service Appointment', verbose_name='Review')),
                ('appointment', models.ForeignKey(help_text='Appointment the Feedback is on', on_delete=django.db.models.deletion.RESTRICT, to='api.appointment', verbose_name='Appointment')),
                ('client', models.ForeignKey(help_text='Client writing the feedback', on_delete=django.db.models.deletion.CASCADE, to='api.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Service Feedback',
                'verbose_name_plural': 'Service Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[api.validators.ExactLengthValidator(14)], verbose_name='National ID')),
                ('birth_date', models.DateField(blank=True, null=True, validators=[api.validators.validate_birth_date], verbose_name='Birth Date')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='api/clients/images', validators=[api.validators.validate_file_size], verbose_name='Client Image')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address', verbose_name='Address')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='api.organization', verbose_name='Organization')),
                ('services_offered', models.ManyToManyField(help_text='Services that this staff member provides.', to='api.service', verbose_name='Services Offered')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workdays', models.ManyToManyField(blank=True, related_name='staff_members', to='api.workday', verbose_name='Staff Working Hours')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
            },
        ),
        migrations.AddField(
            model_name='servicecounter',
            name='staff_member',
            field=models.ForeignKey(help_text='Staff member assigned to this counter', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='counter', to='api.staffmember', verbose_name='Staff Member'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_full_day', models.BooleanField(default=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staffmember')),
            ],
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='api_service_name_a13a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['price'], name='api_service_price_9c7eab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requireddocument',
            unique_together={('service', 'name')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', '-created_at'], name='api_appoint_client__1838e3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'start_time'], name='api_appoint_date_e51875_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['counter', 'date'], name='api_appoint_counter_701316_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_to_pay__gte', 0)), name='positive_amount_to_pay'),
        ),
        migrations.AlterUniqueTogether(
            name='servicefeedback',
            unique_together={('client', 'appointment')},
        ),
        migrations.AlterUniqueTogether(
            name='staffmember',
            unique_together={('user', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('organization', 'name')},
        ),
    ]
