# Generated by Django 5.2.10 on 2026-01-27 18:46

import api.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='servicecounter',
            options={'verbose_name': 'Service Counter', 'verbose_name_plural': 'Service Counters'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default='No-where street, US', max_length=255, verbose_name='Street Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude', max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.organization', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='brief',
            field=models.TextField(blank=True, null=True, verbose_name='Brief'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organization/images', validators=[api.validators.validate_file_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='servicecounter',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_counters', to='api.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='servicecounter',
            name='is_operational',
            field=models.BooleanField(default=True, verbose_name='Is Operational'),
        ),
        migrations.AlterField(
            model_name='servicecounter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='servicecounter',
            name='service',
            field=models.ForeignKey(help_text='Service this counter offers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to='appointment.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='servicecounter',
            name='staff_member',
            field=models.ForeignKey(help_text='Staff member assigned to this counter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter', to='appointment.staffmember', verbose_name='Staff Member'),
        ),
    ]
