# Generated by Django 5.2.11 on 2026-02-25 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.organization', verbose_name='Oraganization'),
        ),
        migrations.AddField(
            model_name='servicecounter',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_counters', to='api.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='servicecounter',
            name='service',
            field=models.ForeignKey(help_text='Service this counter offers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to='appointment.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='servicecounter',
            name='staff_member',
            field=models.ForeignKey(help_text='Staff member assigned to this counter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter', to='appointment.staffmember', verbose_name='Staff Member'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('organization', 'name')},
        ),
    ]
