# Generated by Django 5.2.11 on 2026-04-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacheddocument',
            old_name='requirement',
            new_name='document',
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Document Description'),
        ),
    ]
