# Generated by Django 5.2.11 on 2026-04-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_requirement_attacheddocument_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workday',
            options={'verbose_name': 'Work Day/Operating Hour'},
        ),
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='branch',
            name='operating_hours',
            field=models.ManyToManyField(blank=True, related_name='branches', to='api.workday', verbose_name='Branch Operating Hours'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='workdays',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='api.workday', verbose_name='Staff Working Hours'),
        ),
        migrations.AlterField(
            model_name='servicefeedback',
            name='client',
            field=models.ForeignKey(help_text='Client writing the feedback', on_delete=django.db.models.deletion.CASCADE, to='api.client', verbose_name='Client'),
        ),
        migrations.RemoveField(
            model_name='workday',
            name='staff_member',
        ),
    ]
