# Generated by Django 5.2.10 on 2026-01-29 19:38

import api.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_address_options_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.organization', verbose_name='Oraganization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='api/organizations/images', validators=[api.validators.validate_file_size], verbose_name='Image'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('address', 'city', 'country'), ('latitude', 'longitude')},
        ),
    ]
