# Generated by Django 5.2.10 on 2026-01-29 22:19

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[api.validators.validate_birth_date], verbose_name='Birth Date'),
        ),
    ]
