# Generated by Django 5.2.10 on 2026-01-29 22:20

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_client_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.CharField(max_length=14, unique=True, validators=[api.validators.ExactLengthValidator(14)], verbose_name='National ID'),
        ),
    ]
