# Generated by Django 5.2.10 on 2026-01-30 23:52

from django.db import migrations

STAFF_GROUP = "Service Staff Member"


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name=STAFF_GROUP)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_client_national_id"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
